from enum import Enum

from pydantic import BaseModel, Field


class SeverityLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TelemetryEvent(BaseModel):
    """The incoming payload from the manufacturing/supply chain line."""

    event_id: str = Field(..., description="Unique identifier for the telemetry event")
    supplier_id: str = Field(..., description="ID of the supplier or component")
    anomaly_type: str = Field(
        ..., description="Description of the detected anomaly (e.g., 'Late Shipment', 'Quality Drop')"
    )
    raw_data: str = Field(..., description="Raw string data of the event log")


class RiskAssessment(BaseModel):
    """The structured output generated by the CrewAI Risk Investigator Pod."""

    supplier_id: str = Field(..., description="ID of the investigated supplier")
    severity: SeverityLevel = Field(..., description="Calculated severity of the risk")
    financial_impact_estimate: float = Field(..., description="Estimated cost impact in USD")
    executive_summary: str = Field(..., description="A clear, 2-sentence summary of the risk")
    recommended_action: str = Field(..., description="Recommended mitigation step")


class EscalationAction(BaseModel):
    """The final decision payload sent for Human-in-the-Loop approval."""

    event_id: str = Field(..., description="Associated event ID")
    requires_human_approval: bool = Field(default=True, description="Always True for HIGH/CRITICAL")
    action_type: str = Field(..., description="e.g., 'Halt Production', 'Source Alternate Supplier'")
    justification: str = Field(..., description="Reasoning based on the Risk Assessment")
