from typing import TypedDict

from src.schemas.telemetry import EscalationAction, RiskAssessment, TelemetryEvent


class GraphState(TypedDict):
    """
    The strict enterprise state machine payload.
    This entire object is what gets persisted to Postgres at every node transition,
    satisfying the company zero-trust audit requirements.
    """

    # The initial trigger payload
    event: TelemetryEvent

    # The reasoning output generated by the CrewAI pod
    risk_assessment: RiskAssessment | None

    # The final decision payload awaiting Human-in-the-Loop review
    escalation_action: EscalationAction | None

    # Routing control (determines which node executes next)
    next_node: str

    # Systemic guardrails: Tracking failures or validation errors
    validation_errors: list[str]
